### ISSUE TITLE
multiple array options (featureClass, featureCodes) not usable

### ISSUE THREAD

**Issue by jeffdeville** [pareeohnos/geonames-elixir#1]
# Issue:
http://www.geonames.org/export/geonames-search.html lets you pass a featureClass and featureCode in to limit the results that will be provided. But in order for this to work, they MUST be passed in as:

featureClass=A&featureClass=P

They're currently being passed in as:

featureClass=AP

featureCode will have the same limitation.  I'll work on a PR and submit.

**Comment by pareeohnos** [comment]
Well spotted. As you can see I didn't do a lot of testing :P
PR looks good, will get that merged

**Comment by jeffdeville** [comment]
No worries, I really like the approach you took here! Very clever and succinct.  Happy to contribute just a bit.

**Comment by pareeohnos** [comment]
heh thanks, relatively new to Elixir so glad someone else in the community thinks it's alright :)
