### ISSUE TITLE
mix dependency issue for geonames v1.0.2

### ISSUE THREAD

**Issue by PriyavKaneria** [pareeohnos/geonames-elixir#7]
When installing geonames v1.0.2, the following error came
```
Resolving Hex dependencies...

Failed to use "hackney" because
  httpoison (version 0.11.0) requires ~> 1.6.3
  swoosh (versions 1.3.0 to 1.5.2) requires ~> 1.9


Failed to use "hackney" because
  httpoison (version 0.11.1) requires ~> 1.7.0
  swoosh (versions 1.3.0 to 1.5.2) requires ~> 1.9


Failed to use "hackney" because
  httpoison (version 0.11.2) requires ~> 1.8.0
  swoosh (versions 1.3.0 to 1.5.2) requires ~> 1.9


Failed to use "mime" (versions 2.0.0 to 2.0.2) because
  phoenix_live_dashboard (version 0.6.2) requires ~> 1.6 or ~> 2.0
  swoosh (versions 1.3.0 to 1.3.11) requires ~> 1.1
```
Here is my deps json
```
defp deps do
    [
      {:pbkdf2_elixir, "~> 1.0"},
      {:phoenix, "~> 1.6.4"},
      {:phoenix_ecto, "~> 4.4"},
      {:ecto_sql, "~> 3.6"},
      {:postgrex, ">= 0.0.0"},
      {:phoenix_html, "~> 3.0"},
      {:phoenix_live_reload, "~> 1.2", only: :dev},
      {:phoenix_live_view, "~> 0.17.5"},
      {:floki, ">= 0.30.0", only: :test},
      {:phoenix_live_dashboard, "~> 0.6"},
      {:esbuild, "~> 0.3", runtime: Mix.env() == :dev},
      {:swoosh, "~> 1.3"},
      {:telemetry_metrics, "~> 0.6"},
      {:telemetry_poller, "~> 1.0"},
      {:gettext, "~> 0.18"},
      {:jason, "~> 1.2"},
      {:plug_cowboy, "~> 2.5"},
      {:geonames, "~> 1.0.2"},
      {:poison, "~> 3.0.0"}
    ]
end
```
So I tried to use different versions of swoosh, geonames and httpoison
When I used 
```
...
      {:geonames, "~> 1.0.2"},
      {:poison, "~> 3.0.0"},
      {:httpoison, "~> 1.8.0"}
...
```
I got the following error
```
Resolving Hex dependencies...

Failed to use "httpoison" (version 1.8.0) because
  geonames (versions 1.0.2 and 1.0.3) requires ~> 0.11.0
  mix.exs specifies ~> 1.8.0
```

So why is the latest geonames v1.0.2 requiring httpoison 0.11.0 even though the `mix.exs` file of this package says httpoison 1.8.0?
If there is an issue from my side or any other file I need to share please do let me know, I am a beginner in Elixir as well as Phoenix and really want to use geonames in my new project.
Thank you in advance

**Comment by PriyavKaneria** [comment]
Got the problem
Adding 
```
...
      {:geonames, "~> 1.0.2"},
      {:poison, "~> 3.0.0"},
      {:hackney, "~> 1.18.0", override: true}
...
```
Solved the issue
Very helpful library! Thanks for making 🙏

**Comment by pareeohnos** [comment]
hmm this might be my fault, I haven't actually made a new release since a couple of PR's were merged. if you've installed via mix you'll have version `0.2` which does in fact have `0.11.0` in the mix file. The current version in the `master` branch has a dependency on `1.8` so that might be the cause of the confusion. 

I'll cut a new release `0.3` and then you can hopefully remove that `override` fix

**Comment by PriyavKaneria** [comment]
Oh amazing!
Thank you for the quick response and action 😇

**Comment by pareeohnos** [comment]
ok give that a go. I've published 1.0.3 though I got a minor error at the end, so I'm hoping it worked. If not I'll bump to 1.0.4 and do it again to be sure

**Comment by PriyavKaneria** [comment]
Yeah now no conflicts from geonames lib. Without override still the httpoison and swoosh are conflicting so I'll keep that for now as it is a learning project.
Thank you for the support

**Comment by pareeohnos** [comment]
Ah hang on, I did mess it up. turns out I already published 1.0.3 to hex docs, so my latest publish hasn't done anything. Hang on I'll update again

**Comment by pareeohnos** [comment]
Right ok, 1.0.4 published and actually updated on hexdocs. Give that a go

**Comment by PriyavKaneria** [comment]
Yep! Everything updated smoothly
No errors now even without override
Awesome!
